{
  Region Polska: 1,
  Okręg Północny: 2,
  Okręg Południowy: 3,
  Okręg Zachodni: 4,
  Okręg Halny: 5,
  Okręg NA Wyspach: 6,
  Okręg Śląski: 7,
  Okręg Warszawski: 8,
  Okręg Wschód: 9,
  Grupy Zagraniczne: 10,
  Okręg Online: 11
}