{
  ID: id_bigint,
  Światowe ID: worldid_mixed,
  ID komitetu: service_body_bigint,
  Dzień powszedni: weekday_tinyint,
  Czas rozpoczęcia: start_time,
  Czas trwania: duration_time,
  Formaty: formats,
  Język: lang_enum,
  Długość geograficzna: longitude,
  Szerokość geograficzna: latitude,
  Meeting Name: meeting_name,
  Location Name: location_text,
  Additional Location Information: location_info,
  Street Address: location_street,
  Borough: location_city_subsection,
  Neighborhood: location_neighborhood,
  Town: location_municipality,
  County: location_sub_province,
  State: location_province,
  Zip Code: location_postal_code_1,
  Nation: location_nation,
  Comments: comments,
  Train Lines: train_lines,
  Bus Lines: bus_lines,
  Phone Meeting Dial-in Number: phone_meeting_number,
  Virtual Meeting Link: virtual_meeting_link,
  Virtual Meeting Additional Info: virtual_meeting_additional_info
}